/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import decoradores.AptoDecoradoComAreaDuplex;
import decoradores.AptoDecoradoComBanheira;
import modelos.Apartamento;

/**
 *
 * @author roger
 */
public class ViewApto extends javax.swing.JFrame {

    Apartamento apto;
    AptoDecoradoComBanheira apto1;
    AptoDecoradoComAreaDuplex apto2;

    /**
     * Creates new form ViewApto
     */
    public ViewApto() {
        initComponents();

        apto1 = new AptoDecoradoComBanheira(apto);
        apto2 = new AptoDecoradoComAreaDuplex(apto);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelApartamento = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSaida = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxTipoApto = new javax.swing.JComboBox<>();
        jComboBoxAcessorios = new javax.swing.JComboBox<>();
        jTextFieldValorApto = new javax.swing.JTextField();
        jTextFieldValorDoAcessorio = new javax.swing.JTextField();
        jButtonAdquirir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Decoração de Apartamento");
        setResizable(false);

        jTextAreaSaida.setColumns(20);
        jTextAreaSaida.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSaida);

        jLabel1.setText("Tipo de apartamento:");

        jLabel2.setText("Acessórios:");

        jComboBoxTipoApto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o tipo de apartamento", "Apartamento Básico", "Apartamento Decorado" }));
        jComboBoxTipoApto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxTipoAptoMouseClicked(evt);
            }
        });
        jComboBoxTipoApto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoAptoActionPerformed(evt);
            }
        });

        jComboBoxAcessorios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o tipo de acessório", "Ar Condicionado Ecológico", "Iluminação", "Banheira com Hidromassagem" }));
        jComboBoxAcessorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxAcessoriosMouseClicked(evt);
            }
        });

        jButtonAdquirir.setText("Adquirir");
        jButtonAdquirir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdquirirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelApartamentoLayout = new javax.swing.GroupLayout(jPanelApartamento);
        jPanelApartamento.setLayout(jPanelApartamentoLayout);
        jPanelApartamentoLayout.setHorizontalGroup(
            jPanelApartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanelApartamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelApartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelApartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxTipoApto, 0, 272, Short.MAX_VALUE)
                    .addComponent(jComboBoxAcessorios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelApartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldValorApto)
                    .addComponent(jTextFieldValorDoAcessorio, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)))
            .addGroup(jPanelApartamentoLayout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jButtonAdquirir)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelApartamentoLayout.setVerticalGroup(
            jPanelApartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelApartamentoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelApartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxTipoApto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldValorApto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelApartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxAcessorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldValorDoAcessorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jButtonAdquirir)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelApartamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelApartamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdquirirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdquirirActionPerformed

        

    }//GEN-LAST:event_jButtonAdquirirActionPerformed

    private void jComboBoxTipoAptoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxTipoAptoMouseClicked

        
    }//GEN-LAST:event_jComboBoxTipoAptoMouseClicked

    private void jComboBoxAcessoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxAcessoriosMouseClicked

      
    }//GEN-LAST:event_jComboBoxAcessoriosMouseClicked

    private void jComboBoxTipoAptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoAptoActionPerformed
       
    }//GEN-LAST:event_jComboBoxTipoAptoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewApto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewApto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewApto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewApto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewApto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdquirir;
    private javax.swing.JComboBox<String> jComboBoxAcessorios;
    private javax.swing.JComboBox<String> jComboBoxTipoApto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelApartamento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaSaida;
    private javax.swing.JTextField jTextFieldValorApto;
    private javax.swing.JTextField jTextFieldValorDoAcessorio;
    // End of variables declaration//GEN-END:variables
}
